android {
    compileSdkVersion 34
    defaultConfig {
        applicationId "com.vitbloodbank.app"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            signingConfig signingConfigs.debug
        }
    }
}
